[req]
default_bits  = 2048
default_md = sha256
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no
[req_distinguished_name]
C = US
ST = VA
L = SomeCity
O = WirePod
OU = Vector
CN = wirepod.local
[v3_req]
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = wirepod.local
IP.1 = 192.168.0.142
IP.2 = 192.168.0.190
IP.3 = 192.168.0.118
IP.4 = 192.168.0.113
IP.5 = 127.0.0.1
